CREATE TABLE ACCOUNT (
	ID						BINARY(16)				PRIMARY KEY NOT NULL,
	USERNAME				NVARCHAR(16)			NOT NULL,
	PASSWORD				NVARCHAR(16)			NOT NULL
);

CREATE TABLE ROLE (
	ROLE					NVARCHAR(20)			PRIMARY KEY NOT NULL
);

CREATE TABLE PERMISSION (
	ID						BINARY(16)				PRIMARY KEY NOT NULL,
	PERMISSION				NVARCHAR(16)			NOT NULL,
	ROLE					NVARCHAR(20)			NOT NULL
);

ALTER TABLE PERMISSION
	ADD CONSTRAINT FK_PERMISSION_TO_ROLE FOREIGN KEY (ROLE) REFERENCES ROLE(ROLE);


CREATE TABLE ACCOUNT_ROLE (
	ACCOUNT_ID				BINARY(16)				NOT NULL,
	ROLE					NVARCHAR(20)			NOT NULL,
	PRIMARY KEY (ACCOUNT_ID, ROLE)
);

ALTER TABLE ACCOUNT_ROLE
	ADD CONSTRAINT FK_ACCOUNT_ROLE_TO_ROLE FOREIGN KEY (ROLE) REFERENCES ROLE(ROLE);
ALTER TABLE ACCOUNT_ROLE
	ADD CONSTRAINT FK_ACCOUNT_ROLE_TO_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ID);