CREATE TABLE DOCUMENT_MESSAGES (
	DOCUMENTS_ID			UUID				NOT NULL,
	MESSAGES_ID				UUID				NOT NULL,
	PRIMARY KEY (DOCUMENTS_ID, MESSAGES_ID)
);

CREATE TABLE DOCUMENT (
	ID						UUID				PRIMARY KEY NOT NULL,
	FILE_TYPE				VARCHAR(255)		NOT NULL,
	FILE_NAME				VARCHAR(255)		NOT NULL,
	IS_DELETED				BOOLEAN				NOT NULL DEFAULT TRUE,
	CREATED_BY				UUID				NOT NULL,
	CREATED_ON				TIMESTAMP			NOT NULL,
	UPDATED_BY				UUID				NULL,
	UPDATED_ON				TIMESTAMP			NULL
);

ALTER TABLE DOCUMENT_MESSAGES
	ADD CONSTRAINT FK_DOCUMENT_MESSAGES_TO_MESSAGES FOREIGN KEY (MESSAGES_ID) REFERENCES MESSAGE(ID);
ALTER TABLE DOCUMENT_MESSAGES
	ADD CONSTRAINT FK_DOCUMENT_MESSAGES_TO_DOCUMENTS FOREIGN KEY (DOCUMENTS_ID) REFERENCES DOCUMENT(ID);