CREATE TABLE DOCUMENT_MESSAGES (
	DOCUMENTS_ID				BINARY(16)			NOT NULL,
	MESSAGES_ID				BINARY(16)			NOT NULL,
	PRIMARY KEY (DOCUMENTS_ID, MESSAGES_ID)
);

CREATE TABLE DOCUMENT (
	ID						BINARY(16)			PRIMARY KEY NOT NULL,
	BDATA					LONGBLOB			NOT NULL,
	FILE_TYPE				NVARCHAR(255)		NOT NULL,
	FILE_NAME				NVARCHAR(255)		NOT NULL,
	IS_DELETED				BIT(1)				NOT NULL DEFAULT 0,
	CREATED_BY				BINARY(16)			NOT NULL,
	CREATED_ON				TIMESTAMP			NOT NULL,
	UPDATED_BY				BINARY(16)			NULL,
	UPDATED_ON				TIMESTAMP			NULL
);

ALTER TABLE MESSAGE
	DROP COLUMN BDATA;

ALTER TABLE DOCUMENT_MESSAGES
	ADD CONSTRAINT FK_DOCUMENT_MESSAGES_TO_MESSAGES FOREIGN KEY (MESSAGES_ID) REFERENCES MESSAGE(ID);
ALTER TABLE DOCUMENT_MESSAGES
	ADD CONSTRAINT FK_DOCUMENT_MESSAGES_TO_DOCUMENTS FOREIGN KEY (DOCUMENTS_ID) REFERENCES DOCUMENT(ID);