ALTER TABLE ACCOUNT
	ADD COLUMN IS_DELETED BIT(1)				NOT NULL DEFAULT 0;

CREATE TABLE ROOM (
	ID						BINARY(16)			PRIMARY KEY NOT NULL,
	ROOM_NAME				NVARCHAR(120)		NOT NULL,
	IS_DELETED				BIT(1)				NOT NULL DEFAULT 0,
	CREATED_BY				BINARY(16)		NOT NULL,
	CREATED_ON				TIMESTAMP			NOT NULL,
	UPDATED_BY				BINARY(16)		NULL,
	UPDATED_ON				TIMESTAMP			NULL
);

CREATE TABLE ROOM_ACCOUNT (
	ACCOUNT_ID				BINARY(16)			NOT NULL,
	ROOM_ID					BINARY(16)			NOT NULL,
	PRIMARY KEY (ACCOUNT_ID, ROOM_ID)
);

ALTER TABLE ROOM_ACCOUNT
	ADD CONSTRAINT FK_ROOM_ACCOUNT_TO_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ID);

ALTER TABLE ROOM_ACCOUNT
	ADD CONSTRAINT FK_ROOM_ACCOUNT_TO_ROOM FOREIGN KEY (ROOM_ID) REFERENCES ROOM(ID);

CREATE TABLE MESSAGE (
	ID						BINARY(16)			PRIMARY KEY NOT NULL,
	CONTENT					LONGTEXT			NULL,
	BDATA					LONGBLOB			NULL,
	TYPE					NVARCHAR(20)		NOT NULL,
	ROOM_ID					BINARY(16)			NOT NULL,
	IS_DELETED				BIT(1)				NOT NULL DEFAULT 0,
	CREATED_BY				BINARY(16)			NOT NULL,
	CREATED_ON				TIMESTAMP			NOT NULL,
	UPDATED_BY				BINARY(16)			NULL,
	UPDATED_ON				TIMESTAMP			NULL
);

ALTER TABLE MESSAGE
	ADD CONSTRAINT FK_MESSAGE_TO_ROOM FOREIGN KEY (ROOM_ID) REFERENCES ROOM(ID);