ALTER TABLE ACCOUNT
	ADD COLUMN IS_DELETED BIT(1) NULL DEFAULT 0;

CREATE TABLE ROOM (
	ID						NVARCHAR(36) PRIMARY KEY NOT NULL,
	ROOM_NAME				NVARCHAR(120) NOT NULL,
	IS_DELETED				BIT(1) NULL DEFAULT 0,
	CREATED_BY				NVARCHAR(36) NOT NULL,
	CREATED_ON				TIMESTAMP NOT NULL,
	UPDATED_BY				NVARCHAR(36) NULL,
	UPDATED_ON				TIMESTAMP NULL
);

CREATE TABLE ROOM_ACCOUNT (
	ACCOUNT_ID				NVARCHAR(36) NOT NULL,
	ROOM_ID					NVARCHAR(36) NOT NULL,
	PRIMARY KEY (ACCOUNT_ID, ROOM_ID)
);

ALTER TABLE ROOM_ACCOUNT
	ADD CONSTRAINT FK_ROOM_ACCOUNT_TO_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ID);

ALTER TABLE ROOM_ACCOUNT
	ADD CONSTRAINT FK_ROOM_ACCOUNT_TO_ROOM FOREIGN KEY (ROOM_ID) REFERENCES ROOM(ID);

CREATE TABLE MESSAGE (
	ID						NVARCHAR(36) PRIMARY KEY NOT NULL,
	CONTENT					LONGBLOB NOT NULL,
	TYPE					NVARCHAR(20) NOT NULL,
	ROOM_ID					NVARCHAR(36) NOT NULL,
	IS_DELETED				BIT(1) NULL DEFAULT 0,
	CREATED_BY				NVARCHAR(36) NOT NULL,
	CREATED_ON				TIMESTAMP NOT NULL,
	UPDATED_BY				NVARCHAR(36)NULL,
	UPDATED_ON				TIMESTAMP NULL
);

ALTER TABLE MESSAGE
	ADD CONSTRAINT FK_MESSAGE_TO_ROOM FOREIGN KEY (ROOM_ID) REFERENCES ROOM(ID);