ALTER TABLE ACCOUNT
	ADD COLUMN IS_DELETED	BOOLEAN				NOT NULL DEFAULT TRUE;

CREATE TABLE ROOM (
	ID						UUID				PRIMARY KEY NOT NULL,
	ROOM_NAME				VARCHAR(120)		NOT NULL,
	IS_DELETED				BOOLEAN				NOT NULL DEFAULT TRUE,
	CREATED_BY				UUID				NOT NULL,
	CREATED_ON				TIMESTAMP			NOT NULL,
	UPDATED_BY				UUID				NULL,
	UPDATED_ON				TIMESTAMP			NULL
);

CREATE TABLE ROOM_ACCOUNT (
	ACCOUNT_ID				UUID				NOT NULL,
	ROOM_ID					UUID				NOT NULL,
	PRIMARY KEY (ACCOUNT_ID, ROOM_ID)
);

ALTER TABLE ROOM_ACCOUNT
	ADD CONSTRAINT FK_ROOM_ACCOUNT_TO_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ID);

ALTER TABLE ROOM_ACCOUNT
	ADD CONSTRAINT FK_ROOM_ACCOUNT_TO_ROOM FOREIGN KEY (ROOM_ID) REFERENCES ROOM(ID);

CREATE TABLE MESSAGE (
	ID						UUID				PRIMARY KEY NOT NULL,
	CONTENT					TEXT				NULL,
	TYPE					VARCHAR(20)			NOT NULL,
	ROOM_ID					UUID				NOT NULL,
	IS_DELETED				BOOLEAN				NOT NULL DEFAULT TRUE,
	CREATED_BY				UUID				NOT NULL,
	CREATED_ON				TIMESTAMP			NOT NULL,
	UPDATED_BY				UUID				NULL,
	UPDATED_ON				TIMESTAMP			NULL
);

ALTER TABLE MESSAGE
	ADD CONSTRAINT FK_MESSAGE_TO_ROOM FOREIGN KEY (ROOM_ID) REFERENCES ROOM(ID);