server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

spring:
  profiles:
    active:
    - native
  application:
    name: spring-cloud-config
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/config